apiVersion: dicode/v1
kind: TaskSet
metadata:
  name: dicode-buildin
spec:
  entries:
    webui:
      ref:
        path: ./webui
    notify:
      ref:
        path: ./notify
    tray:
      ref:
        path: ./tray
