// tray/task.ts — System tray daemon for dicode.
//
// Uses a pre-compiled native helper binary (systray-portable) that
// communicates with the Deno process over stdin/stdout JSON.
// No CGO, no GTK, no fyne dependency.

import Systray, { type MenuItem } from "./systray/mod.ts";
import { warnIfTrayInvisible } from "./sni.ts";
import {
  countAttention,
  looksDifferent,
  toRuns,
  type TrayLook,
  trayLook,
} from "./attention.ts";

// ── icon ─────────────────────────────────────────────────────────────────────
//
// 32×32 PNG: purple background (#7c3aed) with a white ⚡ bolt drawn as two
// diagonal bars — matches the icon generated by pkg/tray/icon.go.
//
// Generated offline with the same algorithm as icon.go and base64-encoded so
// this file has zero external asset dependencies.

// 32×32 PNG: purple background (#7c3aed) with a white ⚡ bolt.
// Generated from the same pixel algorithm as the removed pkg/tray/icon.go.
const ICON_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAg0lEQVR4nGKpsXrLQEvARFPTh4UFLJRobj4qBGfXWr/DqmYQBxExzh/EPiDS+YPVB8Q7f1D6gCTnDz4fkOp8fEUFGWZhBST4gDwrGfFUOFTxxIBGMrKrkX1DNQuoAghYQLknBtoHlHtiEPiAQk8MDh9Q4gl8RQVVwKAJosFrASAAAP///MwvLg37TZMAAAAASUVORK5CYII=";

// The same 32×32 icon with a red dot in the top-right, ringed in the icon's own
// purple so the dot stays legible once the bar scales it to 16px.
const ICON_BADGED_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAq0lEQVR42mOssXr7n2EAARPDAIMBdwALrS2otlmIwm89Ek/bEGg+KoTTcmxiTPTyOS45Jmr7vtb6HV7L0R0xfHIBctyPvHIA2ffNR4Uwsho2AFNDsxDA5whkOSZqx32t9Tu8jkAXo3lJSCg6mGjle6rVBdSwhCYhQC2HMRLTIKFlKAyNggjdx+QWu0O7KKZVKAytyogWoTD0qmNqh8LQbJBQMxQYR/uGI94BAN7aRTov5EUDAAAAAElFTkSuQmCC";

const ICONS = { plain: ICON_BASE64, badged: ICON_BADGED_BASE64 };

// How far back to look per task. A run waiting on input is near the top of its
// task's list by construction, so a deep scan buys nothing and costs one IPC
// round trip per task per poll.
const RUN_SCAN_LIMIT = 20;

export default async function main({ params, dicode }: DicodeSdk) {
  // ── platform browser-open helper ─────────────────────────────────────────────

  async function openBrowser(url: string): Promise<void> {
    const os = Deno.build.os;
    let cmd: string[];
    if (os === "linux") {
      cmd = ["xdg-open", url];
    } else if (os === "darwin") {
      cmd = ["open", url];
    } else if (os === "windows") {
      cmd = ["rundll32", "url.dll,FileProtocolHandler", url];
    } else {
      console.warn(`openBrowser: unsupported OS "${os}", cannot open ${url}`);
      return;
    }

    try {
      const proc = new Deno.Command(cmd[0], { args: cmd.slice(1) });
      await proc.spawn().status;
    } catch (err) {
      console.warn(`openBrowser: failed to open ${url}: ${err}`);
    }
  }

  // ── tray setup ───────────────────────────────────────────────────────────────

  // Resolve dashboard port: prefer the DICODE_PORT env var set by dicoded;
  // fall back to 8080.
  const port = parseInt(Deno.env.get("DICODE_PORT") ?? "8080", 10);
  const dashboardURL = `http://localhost:${port}`;

  const menuItems: MenuItem[] = [
    {
      title: "Open Dashboard",
      tooltip: dashboardURL,
      checked: false,
      enabled: true,
    },
    {
      title: "---", // separator (systray convention)
      tooltip: "",
      checked: false,
      enabled: true,
    },
    {
      title: "Quit dicode",
      tooltip: "Stop the dicode server",
      checked: false,
      enabled: true,
    },
  ];

  console.log("tray: starting system tray icon");

  const version = await params.get("tray_version") ?? undefined;

  // Clamped: a sub-second interval would hammer the control plane with one
  // round trip per task, and a non-numeric value must not disable the badge
  // silently.
  const pollSeconds = Math.max(
    5,
    Number(await params.get("attention_poll_seconds")) || 30,
  );

  const systray = new Systray({
    menu: {
      // icon is a base64-encoded PNG string; pass empty string to use the default
      // OS placeholder until ICON_BASE64 is populated (see TODO above).
      icon: ICON_BASE64,
      title: "dicode",
      tooltip: "dicode — automation server",
      items: menuItems,
    },
    debug: false,
    copyDir: true, // copy the native helper binary to a temp dir on first run
    version,
  });

  // ── event loop ───────────────────────────────────────────────────────────────
  //
  // systray.onClick delivers menu-item click events. We never return from this
  // loop; dicoded keeps the daemon alive and will restart it if it exits
  // unexpectedly (trigger.restart: always).

  // Wait for the binary to be downloaded, started, and ready.
  await systray.ready();

  // On bare WMs the SNI icon can be silently invisible; probe after a short
  // grace period so the bar has a chance to register a host first.
  setTimeout(() => {
    warnIfTrayInvisible().catch(() => {});
  }, 3000);

  // ── attention badge ──────────────────────────────────────────────────────────
  //
  // There is no daemon-side "is anything waiting for me" query, so the count is
  // assembled from each task's recent runs. Failures here are swallowed: a tray
  // that cannot count is still a working tray, and restart: always would
  // otherwise turn a transient IPC error into an icon that disappears.

  let shown: TrayLook | null = null;

  async function refreshBadge(): Promise<void> {
    const tasks = await dicode.list_tasks();
    let waiting = 0;
    for (const task of tasks) {
      const runs = await dicode.get_runs(task.id, { limit: RUN_SCAN_LIMIT });
      waiting += countAttention(toRuns(runs));
    }
    const next = trayLook(waiting, ICONS);
    if (!looksDifferent(shown, next)) return;
    await systray.sendAction({
      type: "update-menu",
      menu: {
        icon: next.icon,
        title: "dicode",
        tooltip: next.tooltip,
        items: menuItems,
      },
    });
    shown = next;
  }

  const badgeIntervalMs = pollSeconds * 1000;
  refreshBadge().catch((err) => console.error(`tray: badge refresh: ${err}`));
  setInterval(() => {
    refreshBadge().catch((err) => console.error(`tray: badge refresh: ${err}`));
  }, badgeIntervalMs);

  systray.onClick((action) => {
    switch (action.item.title) {
      case "Open Dashboard":
        openBrowser(dashboardURL).catch((err) =>
          console.error(`tray: openBrowser error: ${err}`)
        );
        break;

      case "Quit dicode":
        console.log("tray: Quit clicked — sending SIGTERM to dicoded");
        systray.kill(false); // shut down the native helper without exiting Deno
        Deno.kill(Deno.ppid, "SIGTERM"); // signal dicoded to shut down gracefully
        break;

      default:
        // separators and unknown items are ignored
        break;
    }
  });

  // Keep the Deno event loop alive indefinitely so the daemon never exits on its
  // own.  dicoded's trigger.restart: always will relaunch it if something goes
  // wrong (e.g. the native helper crashes).
  await new Promise<never>((_resolve) => {});
}
